server:
  servlet:
    context-path: /auth-service
  port: 8080

# OracleDB connection settings
oracledb:
  query:
    defaultTimeout: 30000
  dataSource:
    driverClassName: oracle.jdbc.OracleDriver
    jdbcUrl: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521)))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = orcl)))
    username: dkumar
    password: dkumar
    defaultAutocommit: true
    validationQuery: SELECT 1 FROM DUAL
      
hibernate:
  dialect: org.hibernate.dialect.Oracle12cDialect
  show_sql: true
  hbm2ddl.auto: validate
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  
jwt:
  secret: secret
  expiary: 36000000 # Time in milliseconds