server:
  servlet:
    context-path: /auth-service
  port: 8080

# OracleDB connection settings
mysqldb:
  query:
    defaultTimeout: 30000
  dataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://143.110.242.247:3306/authdb?zeroDateTimeBehavior=convertToNull
    username: root
    password: tj@dialer
    defaultAutocommit: true
      
hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect
  show_sql: true
  hbm2ddl.auto: validate
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  
jwt:
  secret: secret
  expiary: 36000000 # Time in milliseconds
  
spring.main.allow-bean-definition-overriding: true
