
  CREATE TABLE "DKUMAR"."CLIENT_SUBSCRIPTION_DETAILS" 
   (	"ID" NUMBER(*,0), 
	"CLIENT_ID" VARCHAR2(50 BYTE), 
	"PLAN_NAME" VARCHAR2(100 BYTE), 
	"PLAN_EXPIARY" TIMESTAMP (6), 
	"USER_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "DKUMAR"."CLIENT_SUBSCRIPTION_DETAILS_TRIGGER" before
  INSERT ON CLIENT_SUBSCRIPTION_DETAILS FOR EACH row BEGIN
  SELECT CLIENT_SUBSCRIPTION_DETAILS_SEQ.nextval INTO :new.id FROM dual;
END;
/
ALTER TRIGGER "DKUMAR"."CLIENT_SUBSCRIPTION_DETAILS_TRIGGER" ENABLE;




  CREATE TABLE "DKUMAR"."USERS" 
   (	"ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(1000 BYTE), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "DKUMAR"."USER_TRIGGER" before
  INSERT ON USERS FOR EACH row BEGIN
  SELECT USER_SEQ.nextval INTO :new.id FROM dual;
END;
/
ALTER TRIGGER "DKUMAR"."USER_TRIGGER" ENABLE;


CREATE SEQUENCE  "DKUMAR"."CLIENT_SUBSCRIPTION_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE SEQUENCE  "DKUMAR"."USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;



create or replace 
trigger CLIENT_SUBSCRIPTION_DETAILS_trigger before
  INSERT ON CLIENT_SUBSCRIPTION_DETAILS FOR EACH row BEGIN
  SELECT CLIENT_SUBSCRIPTION_DETAILS_SEQ.nextval INTO :new.id FROM dual;
END;


create or replace 
trigger user_trigger before
  INSERT ON USERS FOR EACH row BEGIN
  SELECT USER_SEQ.nextval INTO :new.id FROM dual;
END;